export const ALL_BLOGS_FAIL = "ALL_BLOGS_FAIL";
export const ALL_BLOGS_SUCCESS = "ALL_BLOGS_SUCCESS";
export const ALL_BLOGS_REQUEST = "ALL_BLOGS_REQUEST";


export const GET_SINGLE_BLOG_FAIL = "GET_SINGLE_BLOG_FAIL";
export const GET_SINGLE_BLOG_SUCCESS = "GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_REQUEST= "GET_SINGLE_BLOG_REQUEST";